### ISSUE TITLE
Server on Raspberry Pi 2 B

### ISSUE THREAD

**Issue by Urvishic** [itead/IoTgo#3]
Hi Guys!
I want to load up the IoTgo server on Raspberry Pi.
Can you please guide me to basic requirements on pi?
Any method to do it ..
I am thinking to add up the OS: 

http://blog.hypriot.com/post/hypriotos-back-again-with-docker-on-arm/

then pull the docker to pi.

Please guide
Urvish

**Comment by humingchun** [comment]
Dear URVISH SONI:

Thank you very much for your interest.

From what I know, Raspberry Pi 2 Model B is using ARM Cortex-A7 CPU, so the IoTgo Docker image which is built on x64 CPU will not work. Please refer to [this blog post](http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/).

However, it is possible to run IoTgo on Raspberry Pi 2 even though there are many challenges:
- It is easy to install Nodejs on Raspberry Pi
- It is really not easy to install MongoDB on Raspberry Pi: MongoDB does not provide official support for ARM CPU though [they are working on it](https://jira.mongodb.org/browse/SERVER-1811), there is a MongoDB available for Ubuntu ARM, but it is [too old (2.2.3)](https://launchpad.net/~canonical-arm-dev/+archive/ubuntu/ppa/+build/4372605) and probably not work with IoTgo.

I have found a [docker MongoDB image available for Ubuntu ARM](https://registry.hub.docker.com/u/partlab/ubuntu-arm-mongodb/) but I haven't tried it. There is also someone says [Arch Linux](https://wiki.archlinux.org/index.php/MongoDB) has up-to-date packages for ARM, but you will need to install Arch Linux on Raspberry Pi first.

I personally would suggest you try https://registry.hub.docker.com/u/partlab/ubuntu-arm-mongodb/ first, and if it works on Raspberry Pi, then the rest is easy: you can use it as a base and then install nodejs and IoTgo manually.

Good luck :-)

**Comment by Urvishic** [comment]
Yep Done! Thank you @humingchun !

Arch Linux + Raspberry Pi 2 and your support! Completed Server on Pi!

Working Super Smooth.
But only now thing pending! Sync of 4 switch together.
See I'll elaborate the issue: 

When we do any change on web portal It will be reflected when that switch is getting synced.

ret = sw1.sync()
ret = sw2.sync()
ret = sw3.sync()
ret = sw4.sync()

So is that some cluster arrangement or parallel switch sync that you can suggest.
see I need only for 4 switches. I am connecting 4 switches per board(IoT Node).

Some guidance on this..please

**Comment by mohamedmostafaa** [comment]
can any body help me to finish install iotgo server to the end
