### ISSUE TITLE
Parellel Request processing IoTgo server

### ISSUE THREAD

**Issue by Urvishic** [itead/IoTgo#4]
When we do any change on web portal It will be reflected when that switch is getting synced.
Time is the constraint in this case.
Change refection time becomes to much high sometimes.

ret = sw1.sync()
ret = sw2.sync()
ret = sw3.sync()
ret = sw4.sync()

So is that some cluster arrangement or parallel switch sync that you can suggest.
see I need only for 4 switches. I am connecting 4 switches per board(IoT Node).

Some guidance on this..please

**Comment by humingchun** [comment]
Hi @Urvishic 

IoTgo is only providing HTTP/WebSocket API which we could use to push/pull (HTTP) message send/receive (WebSocket) message, IoTgo also comes with a Web portal which is utilizing those API.

IoTgo itself does not bundle a device SDK, but you can use [ITEADLIB_Arduino_IoTgo](https://github.com/itead/ITEADLIB_Arduino_IoTgo) to connect IoTgo (It seems you are using it). But ITEADLIB_Arduino_IoTgo only wraps HTTP API not WebSocket API. So to get an update, you have to send an HTTP request periodically (such as sw1.sync()), like every one or two seconds.
