### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Urvishic** [itead/IoTgo#5]
Hi @humingchun !

How to use Timer?
Please Guide>..
I have tried but not able to configure time ..
![timer_issue](https://cloud.githubusercontent.com/assets/11005713/8619489/2925195a-2735-11e5-8673-36c2a0600d3e.png)

**Comment by humingchun** [comment]
Hi @Urvishic 

Sorry for late response, I am a little busy these days.

To add a timer, you can use the Web UI as you did, this will create a timer on IoTgo database. For the timer actually works, you need to connect a real device to IoTgo. That device will get timers from IoTgo and actually do the specified action when timer expired.

So, you should check whether the device has received timers info, and have scheduled an action accroding to the timer. I recommend you refer to [ITEADLIB_Arduino_IoTgo](https://github.com/itead/ITEADLIB_Arduino_IoTgo) for device functions.
